'------------------------------------------------------------------------------
' <auto-generated>
'     Este código foi gerado por uma ferramenta.
'
'     Alterações neste arquivo podem causar comportamento incorreto e serão perdidas se
'     o código for gerado novamente. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Confirm

    '''<summary>
    '''Controle successPanel.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Para modificar, mova a declaração de campo do arquivo do Designer para o arquivo code-behind.
    '''</remarks>
    Protected WithEvents successPanel As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''controle de login.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Para modificar, mova a declaração de campo do arquivo do Designer para o arquivo code-behind.
    '''</remarks>
    Protected WithEvents login As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''Controle errorPanel.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Para modificar, mova a declaração de campo do arquivo do Designer para o arquivo code-behind.
    '''</remarks>
    Protected WithEvents errorPanel As Global.System.Web.UI.WebControls.PlaceHolder
End Class
