'------------------------------------------------------------------------------
' <auto-generated>
'     Esse código foi gerado por uma ferramenta.
'
'     As alterações feitas nesse arquivo poderão causar comportamento incorreto e serão perdidas se
'     o código for regenerado. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Manage

    ''' <summary>
    ''' controle SuccessMessagePlaceHolder.
    ''' </summary>
    ''' <remarks>
    ''' Campo gerado automaticamente.
    ''' Para modificar, mova a declaração de campo do arquivo do designer para o arquivo code-behind.
    ''' </remarks>
    Protected WithEvents SuccessMessagePlaceHolder As Global.System.Web.UI.WebControls.PlaceHolder

    ''' <summary>
    ''' Controle ChangePassword.
    ''' </summary>
    ''' <remarks>
    ''' Campo gerado automaticamente.
    ''' Para modificar, mova a declaração de campo do arquivo do designer para o arquivo code-behind.
    ''' </remarks>
    Protected WithEvents ChangePassword As Global.System.Web.UI.WebControls.HyperLink

    ''' <summary>
    ''' Controle CreatePassword.
    ''' </summary>
    ''' <remarks>
    ''' Campo gerado automaticamente.
    ''' Para modificar, mova a declaração de campo do arquivo do designer para o arquivo code-behind.
    ''' </remarks>
    Protected WithEvents CreatePassword As Global.System.Web.UI.WebControls.HyperLink

    ''' <summary>
    ''' Controle PhoneNumber.
    ''' </summary>
    ''' <remarks>
    ''' Campo gerado automaticamente.
    ''' Para modificar, mova a declaração de campo do arquivo do designer para o arquivo code-behind.
    ''' </remarks>
    Protected WithEvents PhoneNumber As Global.System.Web.UI.WebControls.Label
    
End Class
