'------------------------------------------------------------------------------
' <auto-generated>
'     Este código foi gerado por uma ferramenta.
'
'     As alterações feitas nesse arquivo poderão causar comportamento incorreto e serão perdidas se
'     o código for gerado novamente. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class TwoFactorAuthenticationSignIn

    '''<summary>
    '''Controle sendcode.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Para modificar, mova a declaração de campo do arquivo do Designer para o arquivo code-behind.
    '''</remarks>
    Protected WithEvents sendcode As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''Controle Providers.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Para modificar, mova a declaração de campo do arquivo do Designer para o arquivo code-behind.
    '''</remarks>
    Protected WithEvents Providers As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Controle ProviderSubmit.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Para modificar, mova a declaração de campo do arquivo do Designer para o arquivo code-behind.
    '''</remarks>
    Protected WithEvents ProviderSubmit As Global.System.Web.UI.WebControls.Button    

    '''<summary>
    '''Controle verifycode.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Para modificar, mova a declaração de campo do arquivo do Designer para o arquivo code-behind.
    '''</remarks>
    Protected WithEvents verifycode As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''Controle SelectedProvider.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Para modificar, mova a declaração de campo do arquivo do Designer para o arquivo code-behind.
    '''</remarks>
    Protected WithEvents SelectedProvider As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''Controle ErrorMessage.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Para modificar, mova a declaração de campo do arquivo do Designer para o arquivo code-behind.
    '''</remarks>
    Protected WithEvents ErrorMessage As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''Controle FailureText.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Para modificar, mova a declaração de campo do arquivo do Designer para o arquivo code-behind.
    '''</remarks>
    Protected WithEvents FailureText As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Controle Code.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Para modificar, mova a declaração de campo do arquivo do Designer para o arquivo code-behind.
    '''</remarks>
    Protected WithEvents Code As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Controle RememberBrowser.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Para modificar, mova a declaração de campo do arquivo do Designer para o arquivo code-behind.
    '''</remarks>
    Protected WithEvents RememberBrowser As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Controle CodeSubmit.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Para modificar, mova a declaração de campo do arquivo do Designer para o arquivo code-behind.
    '''</remarks>
    Protected WithEvents CodeSubmit As Global.System.Web.UI.WebControls.Button
End Class
