'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class DashBoard_Detail_Colaboradores

    '''<summary>
    '''frm_Mensagem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frm_Mensagem As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''dtrColaboradores control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtrColaboradores As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''Mailto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Mailto As Global.System.Web.UI.HtmlControls.HtmlInputGenericControl

    '''<summary>
    '''Enviar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Enviar As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''dtsColaboradores control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtsColaboradores As Global.System.Web.UI.WebControls.SqlDataSource
End Class
