Imports Microsoft.VisualBasic

Public Class clsEstabelecimentos
	Public Function sql_Estabelecimentos(tipo As String, Optional id As String = "") As String
		Dim sql As String = ""
		sql &= " SELECT "
		sql &= " TBL_ESTABELECIMENTOS_BIH.ID AS Id "
		sql &= " ,TBL_ESTABELECIMENTOS_BIH.CNPJ AS CNPJ "
		sql &= " ,TBL_ESTABELECIMENTOS_BIH.ESTABELECIMENTO AS Estabelecimento "
		sql &= " ,TBL_ESTABELECIMENTOS_BIH.ENDERECO AS Endereco "
		sql &= " ,TBL_ESTABELECIMENTOS_BIH.COMPLEMENTO AS Complemento "
		sql &= " ,TBL_ESTABELECIMENTOS_BIH.BAIRRO AS Bairro "
		sql &= " ,TBL_ESTABELECIMENTOS_BIH.CEP AS CEP "
		sql &= " ,TBL_IBGE_MUNICIPIOS.MUNICIPIO AS Cidade "
		sql &= " ,TBL_IBGE_MUNICIPIOS.UF AS UF "
		sql &= " ,TBL_SETORIZACAO_SETORES.ID_SETOR AS Id_Setor "
		sql &= " ,TBL_SETORIZACAO_SETORES.SETOR AS Setor "
		sql &= " ,TBL_SETORIZACAO_SETORES.EMAIL_RESPONSAVEL AS Email_Representante "
		sql &= " ,REPRESENTANTES.NOME AS Representante "
		sql &= " ,TBL_SETORIZACAO_REGIONAIS.ID_REGIONAL AS Id_Regional "
		sql &= " ,TBL_SETORIZACAO_REGIONAIS.EMAIL_RESPONSAVEL AS Email_Gerente "
		sql &= " ,GERENTES.NOME AS Gerente "
		sql &= " ,TBL_ESTABELECIMENTOS_BIH.ID_GRUPO_ESTABELECIMENTO AS Id_Grupo "
		sql &= " ,TBL_ESTABELECIMENTOS_GRUPOS.GRUPO AS Grupo "
		sql &= " ,TBL_ESTABELECIMENTOS_BIH.COD_ESFERA AS Cod_Esfera "
		sql &= " ,TBL_ESTABELECIMENTOS_ESFERA.ESFERA AS Esfera "
		sql &= " ,TBL_ESTABELECIMENTOS_BIH.ID_GRUPO_DISTRIBUIDOR AS Id_Grupo_Distribuidor "
		sql &= " ,TBL_DISTRIBUIDORES_GRUPOS.GRUPO_DISTRIBUIDOR AS [Grupo Distribuidor] "
		sql &= " FROM "
		sql &= " TBL_IBGE_MUNICIPIOS INNER JOIN TBL_ESTABELECIMENTOS_BIH "
		sql &= " ON TBL_IBGE_MUNICIPIOS.COD_IBGE_7 = TBL_ESTABELECIMENTOS_BIH.COD_IBGE_7 "
		sql &= " INNER JOIN TBL_SETORIZACAO_SETORES "
		sql &= " ON TBL_ESTABELECIMENTOS_BIH.COD_DISTRITO = TBL_SETORIZACAO_SETORES.COD_DISTRITO "
		sql &= " AND TBL_ESTABELECIMENTOS_BIH.COD_REGIONAL = TBL_SETORIZACAO_SETORES.COD_REGIONAL "
		sql &= " AND TBL_ESTABELECIMENTOS_BIH.COD_SETOR = TBL_SETORIZACAO_SETORES.COD_SETOR "
		sql &= " INNER JOIN TBL_USUARIOS AS REPRESENTANTES "
		sql &= " ON TBL_SETORIZACAO_SETORES.EMAIL_RESPONSAVEL = REPRESENTANTES.EMAIL "
		sql &= " INNER JOIN TBL_SETORIZACAO_REGIONAIS	"
		sql &= " ON TBL_SETORIZACAO_SETORES.COD_REGIONAL = TBL_SETORIZACAO_REGIONAIS.COD_REGIONAL "
		sql &= " INNER JOIN TBL_USUARIOS AS GERENTES "
		sql &= " ON TBL_SETORIZACAO_REGIONAIS.EMAIL_RESPONSAVEL = GERENTES.EMAIL "
		sql &= " INNER JOIN TBL_ESTABELECIMENTOS_ESFERA "
		sql &= " ON TBL_ESTABELECIMENTOS_BIH.COD_ESFERA = TBL_ESTABELECIMENTOS_ESFERA.COD_ESFERA "
		sql &= " INNER JOIN TBL_ESTABELECIMENTOS_GRUPOS "
		sql &= " ON TBL_ESTABELECIMENTOS_BIH.ID_GRUPO_ESTABELECIMENTO = TBL_ESTABELECIMENTOS_GRUPOS.ID_GRUPO "
		sql &= " LEFT JOIN TBL_DISTRIBUIDORES_GRUPOS "
		sql &= " ON TBL_ESTABELECIMENTOS_BIH.ID_GRUPO_DISTRIBUIDOR = TBL_DISTRIBUIDORES_GRUPOS.ID_GRUPO_DISTRIBUIDOR "

		If tipo = "lista" Then
			Select Case HttpContext.Current.Session("NIVEL_LOGIN")

				Case = 0
					sql &= " Where TBL_ESTABELECIMENTOS_BIH.CNPJ = '01571702000198'"
				Case = 1
					sql &= " TBL_SETORIZACAO_REGIONAIS.EMAIL_RESPONSAVEL  = '" & HttpContext.Current.Session("EMAIL_LOGIN") & "'"
				Case = 3
					sql &= " Where TBL_SETORIZACAO_SETORES.EMAIL_RESPONSAVEL = '" & HttpContext.Current.Session("EMAIL_LOGIN") & "'"
			End Select
			sql &= " Order By TBL_ESTABELECIMENTOS_BIH.ESTABELECIMENTO "
		End If

		If tipo = "ficha" Then

			sql &= " Where TBL_ESTABELECIMENTOS_BIH.ID = '" & id & "'"

		End If
		sql_Estabelecimentos = sql
	End Function

	Public Function sql_UF(Optional tipo As String = "", Optional id As String = "") As String
		sql_UF = ""
		sql_UF &= " Select '' as UF,  '( Selecione )' as ESTADO Union All"
		sql_UF &= " Select UF, ESTADO From TBL_IBGE_ESTADOS Where UF <> '00' And UF <> 'XX' Order By ESTADO"
	End Function



End Class
