'------------------------------------------------------------------------------
' <auto-generated>
'     Este código foi gerado por uma ferramenta.
'
'     As alterações feitas neste arquivo poderão causar comportamento incorreto e serão perdidas se
'     o código for regenerado. 
' </auto-generated>
'------------------------------------------------------------------------------

Partial Public Class SiteMaster

    ''' <summary>
    ''' Controle A1.
    ''' </summary>
    ''' <remarks>
    ''' Campo gerado automaticamente.
    ''' Para modificar, mova a declaração de campo do arquivo do designer para o arquivo code-behind.
    ''' </remarks>
    Protected A1 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    ''' <summary>
    ''' Controle A2.
    ''' </summary>
    ''' <remarks>
    ''' Campo gerado automaticamente.
    ''' Para modificar, mova a declaração de campo do arquivo do designer para o arquivo code-behind.
    ''' </remarks>
    Protected A2 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    ''' <summary>
    ''' Controle A3.
    ''' </summary>
    ''' <remarks>
    ''' Campo gerado automaticamente.
    ''' Para modificar, mova a declaração de campo do arquivo do designer para o arquivo code-behind.
    ''' </remarks>
    Protected A3 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    ''' <summary>
    ''' Controle A4.
    ''' </summary>
    ''' <remarks>
    ''' Campo gerado automaticamente.
    ''' Para modificar, mova a declaração de campo do arquivo do designer para o arquivo code-behind.
    ''' </remarks>
    Protected A4 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    ''' <summary>
    ''' Controle MainContent.
    ''' </summary>
    ''' <remarks>
    ''' Campo gerado automaticamente.
    ''' Para modificar, mova a declaração de campo do arquivo do designer para o arquivo code-behind.
    ''' </remarks>
    Protected MainContent As Global.System.Web.UI.WebControls.ContentPlaceHolder
End Class
