'------------------------------------------------------------------------------
' <auto-generated>
'     Este código foi gerado por uma ferramenta.
'
'     As alterações feitas nesse arquivo poderão causar comportamento incorreto e serão perdidas se
'     o código for gerado novamente. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AddPhoneNumber

    '''<summary>
    '''Controle ErrorMessage.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Para modificar, mova a declaração de campo do arquivo do Designer para o arquivo code-behind.
    '''</remarks>
    Protected WithEvents ErrorMessage As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Controle PhoneNumber.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Para modificar, mova a declaração de campo do arquivo do Designer para o arquivo code-behind.
    '''</remarks>
    Protected WithEvents PhoneNumber As Global.System.Web.UI.WebControls.TextBox
End Class
