'------------------------------------------------------------------------------
' <auto-generated>
'     Este código foi gerado por uma ferramenta.
'
'     As alterações feitas nesse arquivo poderão causar comportamento incorreto e serão perdidas se
'     o código for gerado novamente. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ManagePassword

    '''<summary>
    '''Controle setPassword.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Para modificar, mova a declaração de campo do arquivo do Designer para o arquivo code-behind.
    '''</remarks>
    Protected WithEvents setPassword As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''Controle password.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Para modificar, mova a declaração de campo do arquivo do Designer para o arquivo code-behind.
    '''</remarks>
    Protected WithEvents password As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''controle confirmPassword.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Para modificar, mova a declaração de campo do arquivo do Designer para o arquivo code-behind.
    '''</remarks>
    Protected WithEvents confirmPassword As Global.System.Web.UI.WebControls.TextBox    

    '''<summary>
    '''Controle changePasswordHolder.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Para modificar, mova a declaração de campo do arquivo do Designer para o arquivo code-behind.
    '''</remarks>
    Protected WithEvents changePasswordHolder As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''Controle CurrentPasswordLabel.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Para modificar, mova a declaração de campo do arquivo do Designer para o arquivo code-behind.
    '''</remarks>
    Protected WithEvents CurrentPasswordLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Controle CurrentPassword.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Para modificar, mova a declaração de campo do arquivo do Designer para o arquivo code-behind.
    '''</remarks>
    Protected WithEvents CurrentPassword As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Controle NewPasswordLabel.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Para modificar, mova a declaração de campo do arquivo do Designer para o arquivo code-behind.
    '''</remarks>
    Protected WithEvents NewPasswordLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Controle NewPassword.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Para modificar, mova a declaração de campo do arquivo do Designer para o arquivo code-behind.
    '''</remarks>
    Protected WithEvents NewPassword As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Controle ConfirmNewPasswordLabel.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Para modificar, mova a declaração de campo do arquivo do Designer para o arquivo code-behind.
    '''</remarks>
    Protected WithEvents ConfirmNewPasswordLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Controle ConfirmNewPassword.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Para modificar, mova a declaração de campo do arquivo do Designer para o arquivo code-behind.
    '''</remarks>
    Protected WithEvents ConfirmNewPassword As Global.System.Web.UI.WebControls.TextBox
End Class
