'------------------------------------------------------------------------------
' <auto-generated>
'     O código foi gerado por uma ferramenta.
'     Versão de Tempo de Execução:4.0.30319.42000
'
'     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
'     o código for gerado novamente.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Este código-fonte foi gerado automaticamente por Microsoft.VSDesigner, Versão 4.0.30319.42000.
'
Namespace svcCEP

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Web.Services.WebServiceBindingAttribute(Name:="CEPSoap", [Namespace]:="SOAWebServices"), _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(Serialization))> _
    Partial Public Class CEP
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol

        Private ConsultaCEPOperationCompleted As System.Threading.SendOrPostCallback

        Private ConsultaCEPEstendidaOperationCompleted As System.Threading.SendOrPostCallback

        Private ConsultaCEPGeoLocalizacaoOperationCompleted As System.Threading.SendOrPostCallback

        Private useDefaultCredentialsSetExplicitly As Boolean

        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.BiHospitalar2020.My.MySettings.Default.CannaMedsBrasil_svcCEP_CEP
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub

        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true) _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false)) _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property

        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property

        '''<remarks/>
        Public Event ConsultaCEPCompleted As ConsultaCEPCompletedEventHandler

        '''<remarks/>
        Public Event ConsultaCEPEstendidaCompleted As ConsultaCEPEstendidaCompletedEventHandler

        '''<remarks/>
        Public Event ConsultaCEPGeoLocalizacaoCompleted As ConsultaCEPGeoLocalizacaoCompletedEventHandler

        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("SOAWebServices/ConsultaCEP", RequestNamespace:="SOAWebServices", ResponseNamespace:="SOAWebServices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function ConsultaCEP(ByVal Credenciais As Credenciais, ByVal CEP As String) As CEP1
            Dim results() As Object = Me.Invoke("ConsultaCEP", New Object() {Credenciais, CEP})
            Return CType(results(0), CEP1)
        End Function

        '''<remarks/>
        Public Overloads Sub ConsultaCEPAsync(ByVal Credenciais As Credenciais, ByVal CEP As String)
            Me.ConsultaCEPAsync(Credenciais, CEP, Nothing)
        End Sub

        '''<remarks/>
        Public Overloads Sub ConsultaCEPAsync(ByVal Credenciais As Credenciais, ByVal CEP As String, ByVal userState As Object)
            If (Me.ConsultaCEPOperationCompleted Is Nothing) Then
                Me.ConsultaCEPOperationCompleted = AddressOf Me.OnConsultaCEPOperationCompleted
            End If
            Me.InvokeAsync("ConsultaCEP", New Object() {Credenciais, CEP}, Me.ConsultaCEPOperationCompleted, userState)
        End Sub

        Private Sub OnConsultaCEPOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultaCEPCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultaCEPCompleted(Me, New ConsultaCEPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub

        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("SOAWebServices/ConsultaCEPEstendida", RequestNamespace:="SOAWebServices", ResponseNamespace:="SOAWebServices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function ConsultaCEPEstendida(ByVal Credenciais As Credenciais, ByVal CEP As String) As CEPEstendida
            Dim results() As Object = Me.Invoke("ConsultaCEPEstendida", New Object() {Credenciais, CEP})
            Return CType(results(0), CEPEstendida)
        End Function

        '''<remarks/>
        Public Overloads Sub ConsultaCEPEstendidaAsync(ByVal Credenciais As Credenciais, ByVal CEP As String)
            Me.ConsultaCEPEstendidaAsync(Credenciais, CEP, Nothing)
        End Sub

        '''<remarks/>
        Public Overloads Sub ConsultaCEPEstendidaAsync(ByVal Credenciais As Credenciais, ByVal CEP As String, ByVal userState As Object)
            If (Me.ConsultaCEPEstendidaOperationCompleted Is Nothing) Then
                Me.ConsultaCEPEstendidaOperationCompleted = AddressOf Me.OnConsultaCEPEstendidaOperationCompleted
            End If
            Me.InvokeAsync("ConsultaCEPEstendida", New Object() {Credenciais, CEP}, Me.ConsultaCEPEstendidaOperationCompleted, userState)
        End Sub

        Private Sub OnConsultaCEPEstendidaOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultaCEPEstendidaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultaCEPEstendidaCompleted(Me, New ConsultaCEPEstendidaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub

        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("SOAWebServices/ConsultaCEPGeoLocalizacao", RequestNamespace:="SOAWebServices", ResponseNamespace:="SOAWebServices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function ConsultaCEPGeoLocalizacao(ByVal Credenciais As Credenciais, ByVal CEP As String) As CEPGeoLocalizacao
            Dim results() As Object = Me.Invoke("ConsultaCEPGeoLocalizacao", New Object() {Credenciais, CEP})
            Return CType(results(0), CEPGeoLocalizacao)
        End Function

        '''<remarks/>
        Public Overloads Sub ConsultaCEPGeoLocalizacaoAsync(ByVal Credenciais As Credenciais, ByVal CEP As String)
            Me.ConsultaCEPGeoLocalizacaoAsync(Credenciais, CEP, Nothing)
        End Sub

        '''<remarks/>
        Public Overloads Sub ConsultaCEPGeoLocalizacaoAsync(ByVal Credenciais As Credenciais, ByVal CEP As String, ByVal userState As Object)
            If (Me.ConsultaCEPGeoLocalizacaoOperationCompleted Is Nothing) Then
                Me.ConsultaCEPGeoLocalizacaoOperationCompleted = AddressOf Me.OnConsultaCEPGeoLocalizacaoOperationCompleted
            End If
            Me.InvokeAsync("ConsultaCEPGeoLocalizacao", New Object() {Credenciais, CEP}, Me.ConsultaCEPGeoLocalizacaoOperationCompleted, userState)
        End Sub

        Private Sub OnConsultaCEPGeoLocalizacaoOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultaCEPGeoLocalizacaoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultaCEPGeoLocalizacaoCompleted(Me, New ConsultaCEPGeoLocalizacaoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub

        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub

        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing) _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024) _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="SOAWebServices")> _
    Partial Public Class Credenciais

        Private emailField As String

        Private senhaField As String

        '''<remarks/>
        Public Property Email() As String
            Get
                Return Me.emailField
            End Get
            Set
                Me.emailField = value
            End Set
        End Property

        '''<remarks/>
        Public Property Senha() As String
            Get
                Return Me.senhaField
            End Get
            Set
                Me.senhaField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="SOAWebServices")> _
    Partial Public Class Transacao

        Private statusField As Boolean

        Private codigoStatusField As String

        Private codigoStatusDescricaoField As String

        '''<remarks/>
        Public Property Status() As Boolean
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property

        '''<remarks/>
        Public Property CodigoStatus() As String
            Get
                Return Me.codigoStatusField
            End Get
            Set
                Me.codigoStatusField = value
            End Set
        End Property

        '''<remarks/>
        Public Property CodigoStatusDescricao() As String
            Get
                Return Me.codigoStatusDescricaoField
            End Get
            Set
                Me.codigoStatusDescricaoField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(GeoLocalizacao)), _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(CEPGeoLocalizacao)), _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(CEPEstendida)), _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(CEP1)), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="SOAWebServices")> _
    Partial Public Class Serialization
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="SOAWebServices")> _
    Partial Public Class GeoLocalizacao
        Inherits Serialization

        Private latitudeField As Decimal

        Private longitudeField As Decimal

        '''<remarks/>
        Public Property Latitude() As Decimal
            Get
                Return Me.latitudeField
            End Get
            Set
                Me.latitudeField = value
            End Set
        End Property

        '''<remarks/>
        Public Property Longitude() As Decimal
            Get
                Return Me.longitudeField
            End Get
            Set
                Me.longitudeField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="SOAWebServices")> _
    Partial Public Class CEPGeoLocalizacao
        Inherits Serialization

        Private cEPField As String

        Private tipoLogradouroField As String

        Private logradouroField As String

        Private logradouroCompletoField As String

        Private logradouroComplementoField As String

        Private bairroField As String

        Private bairroComplementoField As String

        Private geoLocalizacaoLogradouroField As GeoLocalizacao

        Private ufField As String

        Private estadoField As String

        Private cidadeField As String

        Private codigoIBGEField As String

        Private geoLocalizacaoCidadeField As GeoLocalizacao

        Private mensagemField As String

        Private statusField As Boolean

        Private transacaoField As Transacao

        '''<remarks/>
        Public Property CEP() As String
            Get
                Return Me.cEPField
            End Get
            Set
                Me.cEPField = value
            End Set
        End Property

        '''<remarks/>
        Public Property TipoLogradouro() As String
            Get
                Return Me.tipoLogradouroField
            End Get
            Set
                Me.tipoLogradouroField = value
            End Set
        End Property

        '''<remarks/>
        Public Property Logradouro() As String
            Get
                Return Me.logradouroField
            End Get
            Set
                Me.logradouroField = value
            End Set
        End Property

        '''<remarks/>
        Public Property LogradouroCompleto() As String
            Get
                Return Me.logradouroCompletoField
            End Get
            Set
                Me.logradouroCompletoField = value
            End Set
        End Property

        '''<remarks/>
        Public Property LogradouroComplemento() As String
            Get
                Return Me.logradouroComplementoField
            End Get
            Set
                Me.logradouroComplementoField = value
            End Set
        End Property

        '''<remarks/>
        Public Property Bairro() As String
            Get
                Return Me.bairroField
            End Get
            Set
                Me.bairroField = value
            End Set
        End Property

        '''<remarks/>
        Public Property BairroComplemento() As String
            Get
                Return Me.bairroComplementoField
            End Get
            Set
                Me.bairroComplementoField = value
            End Set
        End Property

        '''<remarks/>
        Public Property GeoLocalizacaoLogradouro() As GeoLocalizacao
            Get
                Return Me.geoLocalizacaoLogradouroField
            End Get
            Set
                Me.geoLocalizacaoLogradouroField = value
            End Set
        End Property

        '''<remarks/>
        Public Property UF() As String
            Get
                Return Me.ufField
            End Get
            Set
                Me.ufField = value
            End Set
        End Property

        '''<remarks/>
        Public Property Estado() As String
            Get
                Return Me.estadoField
            End Get
            Set
                Me.estadoField = value
            End Set
        End Property

        '''<remarks/>
        Public Property Cidade() As String
            Get
                Return Me.cidadeField
            End Get
            Set
                Me.cidadeField = value
            End Set
        End Property

        '''<remarks/>
        Public Property CodigoIBGE() As String
            Get
                Return Me.codigoIBGEField
            End Get
            Set
                Me.codigoIBGEField = value
            End Set
        End Property

        '''<remarks/>
        Public Property GeoLocalizacaoCidade() As GeoLocalizacao
            Get
                Return Me.geoLocalizacaoCidadeField
            End Get
            Set
                Me.geoLocalizacaoCidadeField = value
            End Set
        End Property

        '''<remarks/>
        Public Property Mensagem() As String
            Get
                Return Me.mensagemField
            End Get
            Set
                Me.mensagemField = value
            End Set
        End Property

        '''<remarks/>
        Public Property Status() As Boolean
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property

        '''<remarks/>
        Public Property Transacao() As Transacao
            Get
                Return Me.transacaoField
            End Get
            Set
                Me.transacaoField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="SOAWebServices")> _
    Partial Public Class CEPEstendida
        Inherits Serialization

        Private cEPField As String

        Private tipoLogradouroField As String

        Private logradouroField As String

        Private logradouroCompletoField As String

        Private logradouroComplementoField As String

        Private bairroField As String

        Private bairroComplementoField As String

        Private ufField As String

        Private estadoField As String

        Private cidadeField As String

        Private codigoIBGEField As String

        Private mensagemField As String

        Private statusField As Boolean

        Private transacaoField As Transacao

        '''<remarks/>
        Public Property CEP() As String
            Get
                Return Me.cEPField
            End Get
            Set
                Me.cEPField = value
            End Set
        End Property

        '''<remarks/>
        Public Property TipoLogradouro() As String
            Get
                Return Me.tipoLogradouroField
            End Get
            Set
                Me.tipoLogradouroField = value
            End Set
        End Property

        '''<remarks/>
        Public Property Logradouro() As String
            Get
                Return Me.logradouroField
            End Get
            Set
                Me.logradouroField = value
            End Set
        End Property

        '''<remarks/>
        Public Property LogradouroCompleto() As String
            Get
                Return Me.logradouroCompletoField
            End Get
            Set
                Me.logradouroCompletoField = value
            End Set
        End Property

        '''<remarks/>
        Public Property LogradouroComplemento() As String
            Get
                Return Me.logradouroComplementoField
            End Get
            Set
                Me.logradouroComplementoField = value
            End Set
        End Property

        '''<remarks/>
        Public Property Bairro() As String
            Get
                Return Me.bairroField
            End Get
            Set
                Me.bairroField = value
            End Set
        End Property

        '''<remarks/>
        Public Property BairroComplemento() As String
            Get
                Return Me.bairroComplementoField
            End Get
            Set
                Me.bairroComplementoField = value
            End Set
        End Property

        '''<remarks/>
        Public Property UF() As String
            Get
                Return Me.ufField
            End Get
            Set
                Me.ufField = value
            End Set
        End Property

        '''<remarks/>
        Public Property Estado() As String
            Get
                Return Me.estadoField
            End Get
            Set
                Me.estadoField = value
            End Set
        End Property

        '''<remarks/>
        Public Property Cidade() As String
            Get
                Return Me.cidadeField
            End Get
            Set
                Me.cidadeField = value
            End Set
        End Property

        '''<remarks/>
        Public Property CodigoIBGE() As String
            Get
                Return Me.codigoIBGEField
            End Get
            Set
                Me.codigoIBGEField = value
            End Set
        End Property

        '''<remarks/>
        Public Property Mensagem() As String
            Get
                Return Me.mensagemField
            End Get
            Set
                Me.mensagemField = value
            End Set
        End Property

        '''<remarks/>
        Public Property Status() As Boolean
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property

        '''<remarks/>
        Public Property Transacao() As Transacao
            Get
                Return Me.transacaoField
            End Get
            Set
                Me.transacaoField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(TypeName:="CEP", [Namespace]:="SOAWebServices")> _
    Partial Public Class CEP1
        Inherits Serialization

        Private cEPField As String

        Private tipoLogradouroField As String

        Private logradouroField As String

        Private bairroField As String

        Private ufField As String

        Private estadoField As String

        Private cidadeField As String

        Private codigoIBGEField As String

        Private mensagemField As String

        Private statusField As Boolean

        Private transacaoField As Transacao

        '''<remarks/>
        Public Property CEP() As String
            Get
                Return Me.cEPField
            End Get
            Set
                Me.cEPField = value
            End Set
        End Property

        '''<remarks/>
        Public Property TipoLogradouro() As String
            Get
                Return Me.tipoLogradouroField
            End Get
            Set
                Me.tipoLogradouroField = value
            End Set
        End Property

        '''<remarks/>
        Public Property Logradouro() As String
            Get
                Return Me.logradouroField
            End Get
            Set
                Me.logradouroField = value
            End Set
        End Property

        '''<remarks/>
        Public Property Bairro() As String
            Get
                Return Me.bairroField
            End Get
            Set
                Me.bairroField = value
            End Set
        End Property

        '''<remarks/>
        Public Property UF() As String
            Get
                Return Me.ufField
            End Get
            Set
                Me.ufField = value
            End Set
        End Property

        '''<remarks/>
        Public Property Estado() As String
            Get
                Return Me.estadoField
            End Get
            Set
                Me.estadoField = value
            End Set
        End Property

        '''<remarks/>
        Public Property Cidade() As String
            Get
                Return Me.cidadeField
            End Get
            Set
                Me.cidadeField = value
            End Set
        End Property

        '''<remarks/>
        Public Property CodigoIBGE() As String
            Get
                Return Me.codigoIBGEField
            End Get
            Set
                Me.codigoIBGEField = value
            End Set
        End Property

        '''<remarks/>
        Public Property Mensagem() As String
            Get
                Return Me.mensagemField
            End Get
            Set
                Me.mensagemField = value
            End Set
        End Property

        '''<remarks/>
        Public Property Status() As Boolean
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property

        '''<remarks/>
        Public Property Transacao() As Transacao
            Get
                Return Me.transacaoField
            End Get
            Set
                Me.transacaoField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")> _
    Public Delegate Sub ConsultaCEPCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultaCEPCompletedEventArgs)

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code")> _
    Partial Public Class ConsultaCEPCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs

        Private results() As Object

        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub

        '''<remarks/>
        Public ReadOnly Property Result() As CEP1
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0), CEP1)
            End Get
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")> _
    Public Delegate Sub ConsultaCEPEstendidaCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultaCEPEstendidaCompletedEventArgs)

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code")> _
    Partial Public Class ConsultaCEPEstendidaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs

        Private results() As Object

        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub

        '''<remarks/>
        Public ReadOnly Property Result() As CEPEstendida
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0), CEPEstendida)
            End Get
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")> _
    Public Delegate Sub ConsultaCEPGeoLocalizacaoCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultaCEPGeoLocalizacaoCompletedEventArgs)

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code")> _
    Partial Public Class ConsultaCEPGeoLocalizacaoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs

        Private results() As Object

        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub

        '''<remarks/>
        Public ReadOnly Property Result() As CEPGeoLocalizacao
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0), CEPGeoLocalizacao)
            End Get
        End Property
    End Class
End Namespace
